version: '3.7'
services:
  service-a:
    container_name: service-a
    build:
      context: ./microservices/service-a
      dockerfile: Dockerfile.dev
    working_dir: /app
    ports:
      - 8080:8080
    volumes:
      - ./microservices/service-a/:/app
    networks:
      - server

  service-b:
    container_name: service-b
    build:
      context: ./microservices/service-b
      dockerfile: Dockerfile.dev
    working_dir: /app
    ports:
      - 8081:8081
    volumes:
      - ./microservices/service-b/:/app
      - ./microservices/service-b/config.json:/app/config.json
    networks:
      - server

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin-slim:latest
    ports:
      - 9411:9411
    networks:
      - server

networks: 
  server:
    driver: bridge